### ISSUE TITLE
#17 ASIGNACIÓN DE TRAMITES

### ISSUE THREAD

**Issue by Jolverm** [Jolverm/agel237#17]
Desde que un usuario (asistente ) crea una tarea se agrega a un asignado (que puede o no ser definitivo), por lo que lo mas practico seria que en la asignación de tareas tomara ese valor y de ahi con el select el usuario (administrador) confirme o modifique, para pasar a la pantalla de asignacion de TEL/AUTO

**Comment by emxkohd** [comment]
Eso ya lo hace no?
